version: '3'
services:
  backend:
    #restart: always
    networks:
      - database
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - HMAC_SECRET_KEY=${HMAC_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_HOST=mysql
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
      - PORT=${PORT}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - /backend:/app
    depends_on:
      - mysql

  frontend:
    #restart: always
    build: ./frontend
    ports:
      - "5173:80"
    volumes:
      - /frontend:/app

  mysql:
    #restart: always
    networks:
      - database
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


networks:
  database:
