import { MigrationInterface, QueryRunner } from 'typeorm';

export class PictureSeed1697626803061 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`INSERT INTO \`picture\`(url, productId) VALUES 
    ("/uploads/woman-jean-blond-1.jpeg", 1),
    ("/uploads/woman-jean-blond-2.jpeg", 1),
    ("/uploads/woman-jean-carhart-1.jpeg", 2),
    ("/uploads/woman-jean-carhart-2.jpeg", 2),
    ("/uploads/woman-jean-eight-1.jpeg", 3),
    ("/uploads/woman-jean-eight-2.jpeg", 3),
    ("/uploads/woman-jean-elephant-1.jpeg", 4),
    ("/uploads/woman-jean-elephant-2.jpeg", 4),
    ("/uploads/woman-hat-black-1.jpeg", 5),
    ("/uploads/woman-hat-black-2.jpeg", 5),
    ("/uploads/woman-hat-chapka-1.jpeg", 6),
    ("/uploads/woman-hat-chapka-2.jpeg", 6),
    ("/uploads/woman-hat-red-1.jpeg", 7),
    ("/uploads/woman-hat-red-2.jpeg", 7),
    ("/uploads/woman-pants-black-1.jpeg", 8),
    ("/uploads/woman-pants-black-2.jpeg", 8),
    ("/uploads/woman-pants-gold-1.jpeg", 9),
    ("/uploads/woman-pants-gold-2.jpeg", 9),
    ("/uploads/woman-pants-pink-1.jpeg", 10),
    ("/uploads/woman-pants-pink-2.jpeg", 10),
    ("/uploads/woman-pants-pink-3.jpeg", 10),
    ("/uploads/woman-pants-red-1.jpeg", 11),
    ("/uploads/woman-pants-red-2.jpeg", 11),
    ("/uploads/woman-pants-yellow-1.jpeg", 12),
    ("/uploads/woman-pull-green-1.jpeg", 13),
    ("/uploads/woman-pull-green-2.jpeg", 13),
    ("/uploads/woman-pull-green-3.jpeg", 13),
    ("/uploads/woman-pull-white-1.jpeg", 14),
    ("/uploads/woman-pull-white-2.jpeg", 14),
    ("/uploads/woman-robe-blue-1.jpeg", 15),
    ("/uploads/woman-robe-blue-2.jpeg", 15),
    ("/uploads/woman-robe-blue-3.jpeg", 15),
    ("/uploads/woman-robe-blue-4.jpeg", 15),
    ("/uploads/woman-robe-blue-5.jpeg", 15),
    ("/uploads/woman-robe-blue-6.jpeg", 15),
    ("/uploads/woman-robe-brown-1.jpeg", 16),
    ("/uploads/woman-robe-brown-2.jpeg", 16),
    ("/uploads/woman-robe-brown-3.jpeg", 16),
    ("/uploads/woman-robe-green-1.jpeg", 17),
    ("/uploads/woman-robe-green-2.jpeg", 17),
    ("/uploads/woman-robe-green-3.jpeg", 17),
    ("/uploads/woman-robe-green-4.jpeg", 17),
    ("/uploads/woman-robe-pink-1.jpeg", 18),
    ("/uploads/woman-robe-pink-2.jpeg", 18),
    ("/uploads/woman-robe-red-1.jpeg", 19),
    ("/uploads/woman-robe-red-2.jpeg", 19),
    ("/uploads/woman-robe-red-3.jpeg", 19),
    ("/uploads/woman-scarf-beige-1.jpeg", 20),
    ("/uploads/woman-scarf-beige-2.jpeg", 20),
    ("/uploads/woman-scarf-green-1.jpeg", 21),
    ("/uploads/woman-scarf-green-2.jpeg", 21),
    ("/uploads/woman-shirt-beige-1.jpeg", 22),
    ("/uploads/woman-shirt-beige-2.jpeg", 22),
    ("/uploads/woman-shirt-beige-3.jpeg", 22),
    ("/uploads/woman-shirt-green-1.jpeg", 23),
    ("/uploads/woman-shirt-green-2.jpeg", 23),
    ("/uploads/woman-shirt-grey-1.jpeg", 24),
    ("/uploads/woman-shirt-grey-2.jpeg", 24),
    ("/uploads/woman-shirt-white-1.jpeg", 25),
    ("/uploads/woman-shirt-white-2.jpeg", 25),
    ("/uploads/woman-shoes-beige-1.jpeg", 26),
    ("/uploads/woman-shoes-beige-2.jpeg", 26),
    ("/uploads/woman-shoes-beige-3.jpeg", 26),
    ("/uploads/woman-shoes-black-1.jpeg", 27),
    ("/uploads/woman-shoes-black-2.jpeg", 27),
    ("/uploads/woman-shoes-gold-1.jpeg", 28),
    ("/uploads/woman-shoes-gold-2.jpeg", 28),
    ("/uploads/woman-shoes-gold-3.jpeg", 28),
    ("/uploads/woman-shoes-red-1.jpeg", 29),
    ("/uploads/woman-shoes-red-2.jpeg", 29),
    ("/uploads/woman-short-beige-1.jpeg", 30),
    ("/uploads/woman-short-beige-2.jpeg", 30),
    ("/uploads/woman-short-beige-3.jpeg", 30),
    ("/uploads/woman-short-brown-1.jpeg", 31),
    ("/uploads/woman-short-jean-1.jpeg", 32),
    ("/uploads/woman-short-jean-2.jpeg", 32),
    ("/uploads/woman-short-pink-1.jpeg", 33),
    ("/uploads/woman-short-pink-2.jpeg", 33),
    ("/uploads/woman-t-shirt-beige-1.jpeg", 34),
    ("/uploads/woman-t-shirt-blue-1.jpeg", 35),
    ("/uploads/woman-t-shirt-blue-2.jpeg", 35),
    ("/uploads/woman-t-shirt-white-1.jpeg", 36),
    ("/uploads/woman-t-shirt-white-2.jpeg", 36),
    ("/uploads/woman-t-shirt-white-3.jpeg", 36),
    ("/uploads/woman-underwear-beige-1.jpeg", 37),
    ("/uploads/woman-underwear-beige-2.jpeg", 37),
    ("/uploads/woman-underwear-beige-3.jpeg", 37),
    ("/uploads/woman-underwear-black-1.jpeg", 38),
    ("/uploads/woman-underwear-black-2.jpeg", 38),
    ("/uploads/woman-underwear-brown-1.jpeg", 39),
    ("/uploads/woman-underwear-brown-2.jpeg", 39),
    ("/uploads/woman-underwear-pink-1.jpeg", 40),
    ("/uploads/woman-underwear-pink-2.jpeg", 40),
    ("/uploads/woman-underwear-red-1.jpeg", 41),
    ("/uploads/woman-veste-red-1.jpeg", 42);`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`SET FOREIGN_KEY_CHECKS=0`);

    await queryRunner.query(`DELETE FROM \`picture\``);
  }
}
